import type { Client, Ad, Competitor, CompetitorAd, DashboardMetrics, SpendChartPoint } from '@/types'

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Natura & Co',
    color: '#10B981',
    meta_account_id: '123456789',
    is_active: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'Boticário',
    color: '#6366F1',
    meta_account_id: '987654321',
    is_active: true,
    created_at: '2024-02-01T00:00:00Z',
  },
]

export const mockAds: Ad[] = [
  {
    id: 'a1',
    client_id: '1',
    ad_id: 'meta_001',
    ad_name: 'Promoção Verão - Crème Hidratante',
    campaign_name: 'Conversão - Black Friday',
    adset_name: 'Público Lookalike 1-3%',
    status: 'ACTIVE',
    spend: 4820.50,
    impressions: 312000,
    clicks: 8400,
    ctr: 2.69,
    cpl: 38.20,
    cpc: 0.57,
    reach: 210000,
    creative_body: 'Hidrate sua pele com o melhor da natureza. Crème Hidratante Natura com desconto especial. Compre agora!',
    platform: 'meta',
    objective: 'CONVERSIONS',
    last_synced_at: new Date().toISOString(),
    client: mockClients[0],
  },
  {
    id: 'a2',
    client_id: '1',
    ad_id: 'meta_002',
    ad_name: 'Vídeo Institucional - Tododia',
    campaign_name: 'Topo de Funil - Reconhecimento',
    adset_name: 'Interesse Beleza/Skincare',
    status: 'ACTIVE',
    spend: 2100.00,
    impressions: 890000,
    clicks: 5300,
    ctr: 0.60,
    cpl: 62.50,
    cpc: 0.40,
    reach: 670000,
    creative_body: 'Descubra a linha Tododia Natura. Cheiros incríveis, pele macia o dia todo.',
    platform: 'meta',
    objective: 'REACH',
    last_synced_at: new Date().toISOString(),
    client: mockClients[0],
  },
  {
    id: 'a3',
    client_id: '2',
    ad_id: 'meta_003',
    ad_name: 'Lançamento Egeo Paradise',
    campaign_name: 'Lançamento - Egeo',
    adset_name: 'Retargeting 30 dias',
    status: 'ACTIVE',
    spend: 7350.00,
    impressions: 540000,
    clicks: 14200,
    ctr: 2.63,
    cpl: 28.40,
    cpc: 0.52,
    reach: 380000,
    creative_body: 'Egeo Paradise chegou! O perfume que vai te transportar para o paraíso. 🌴',
    platform: 'meta',
    objective: 'CONVERSIONS',
    last_synced_at: new Date().toISOString(),
    client: mockClients[1],
  },
  {
    id: 'a4',
    client_id: '2',
    ad_id: 'meta_004',
    ad_name: 'Kit Presente Dia das Mães',
    campaign_name: 'Datas Comemorativas',
    adset_name: 'Público Frio - Mães 25-55',
    status: 'ACTIVE',
    spend: 3200.00,
    impressions: 210000,
    clicks: 6800,
    ctr: 3.24,
    cpl: 22.00,
    cpc: 0.47,
    reach: 145000,
    creative_body: 'O presente perfeito para o Dia das Mães. Kits exclusivos Boticário com desconto especial.',
    platform: 'meta',
    objective: 'CONVERSIONS',
    last_synced_at: new Date().toISOString(),
    client: mockClients[1],
  },
]

export const mockCompetitors: Competitor[] = [
  {
    id: 'c1',
    name: 'L\'Oréal Brasil',
    facebook_page_id: '12345',
    facebook_page_name: 'L\'Oréal Paris Brasil',
    industry: 'Beleza',
    website: 'https://www.loreal-paris.com.br',
    created_at: '2024-03-01T00:00:00Z',
    _ads_count: 12,
  },
  {
    id: 'c2',
    name: 'Avon Brasil',
    facebook_page_id: '67890',
    facebook_page_name: 'Avon Brasil',
    industry: 'Beleza & Cosméticos',
    website: 'https://www.avon.com.br',
    created_at: '2024-03-15T00:00:00Z',
    _ads_count: 8,
  },
]

export const mockCompetitorAds: CompetitorAd[] = [
  {
    id: 'ca1',
    competitor_id: 'c1',
    ad_archive_id: 'lib_001',
    creative_body: 'Porque você vale muito. Nova linha Revitalift com tecnologia Pro-Retinol. Pele visivelmente mais jovem em 7 dias. ✨',
    ad_snapshot_url: '',
    status: 'ACTIVE',
    impressions_lower: 500000,
    impressions_upper: 1000000,
    spend_lower: 5000,
    spend_upper: 10000,
    started_at: '2024-11-01',
    last_seen_at: new Date().toISOString().split('T')[0],
    platforms: ['facebook', 'instagram'],
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'ca2',
    competitor_id: 'c1',
    ad_archive_id: 'lib_002',
    creative_body: '🎁 Presente de Natal perfeito! Kit Elvive com 40% off. Só até domingo!',
    ad_snapshot_url: '',
    status: 'ACTIVE',
    impressions_lower: 200000,
    impressions_upper: 500000,
    spend_lower: 2000,
    spend_upper: 5000,
    started_at: '2024-12-01',
    last_seen_at: new Date().toISOString().split('T')[0],
    platforms: ['facebook', 'instagram', 'audience_network'],
    last_synced_at: new Date().toISOString(),
  },
  {
    id: 'ca3',
    competitor_id: 'c2',
    ad_archive_id: 'lib_003',
    creative_body: 'Seja sua própria chefe. Revenda Avon e ganhe mais! Cadastre-se grátis agora.',
    ad_snapshot_url: '',
    status: 'ACTIVE',
    impressions_lower: 1000000,
    impressions_upper: 5000000,
    spend_lower: 10000,
    spend_upper: 50000,
    started_at: '2024-09-01',
    last_seen_at: new Date().toISOString().split('T')[0],
    platforms: ['facebook', 'instagram'],
    ai_insights: JSON.stringify({
      what_works: 'Apela para empoderamento financeiro feminino com baixa barreira de entrada ("grátis").',
      angle: 'Oportunidade de renda + independência — não foca no produto em si.',
      adaptation_suggestion: 'Testar criativo focado em "ganhe dinheiro indicando" para seus clientes com programa de indicação.',
    }),
    last_synced_at: new Date().toISOString(),
  },
]

export const mockMetrics: DashboardMetrics = {
  total_spend: 17470.50,
  total_impressions: 1952000,
  total_clicks: 34700,
  avg_ctr: 1.78,
  avg_cpl: 34.20,
  active_ads: 4,
  active_clients: 2,
}

export const mockSpendChart: SpendChartPoint[] = [
  { date: '20 Mai', 'Natura & Co': 620, Boticário: 980 },
  { date: '21 Mai', 'Natura & Co': 710, Boticário: 1100 },
  { date: '22 Mai', 'Natura & Co': 580, Boticário: 870 },
  { date: '23 Mai', 'Natura & Co': 820, Boticário: 1250 },
  { date: '24 Mai', 'Natura & Co': 940, Boticário: 1400 },
  { date: '25 Mai', 'Natura & Co': 1100, Boticário: 1600 },
  { date: '26 Mai', 'Natura & Co': 1150, Boticário: 1700 },
]
